---
title: "algorytmy"
author: "Marta Boraty"
date: '2024-05-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message=FALSE,error=FALSE,fig.width = 12)
```

```{r,warning=FALSE, message=FALSE,error=FALSE}

library(cluster)
library(dplyr)
library(ggplot2)
library(outliers)
library(corrplot)
library(gridExtra)
library(reshape2)
library(tidyr)
library(xtable)
library(dtwclust)
library(skmeans)
library(fossil)
library(fclust)
setwd('C:/Users/user/Desktop/magisterka/skrypty')
source("funkcje.R")
source("ssfcm.R")
library(rmarkdown)
source("preprocessing_1.R")
bd <- read.csv('mmdata_imp.csv',header=TRUE)
#library(caret)
set.seed(156)
```
















```{r,warnings=FALSE, message=FALSE,error=FALSE}
columns_pca <- c("pca1","pca2")
thres <- c(0.5,0.10,0.20,0.30)
results_t <- list()
for (t in 1:length(thres)){
  mod <- models_dynamic(data_15,2,p=0,C=2,'assfcm',columns_pca,'euthymia','eu_50',threshold = thres[t],x_lim=c(-0.25,0.25),y_lim=c(-0.25,0.25),iteration=t)
  results_t[[t]] <- mod$results
}
results_t
```
```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")

plot1 <- ggplot(data_15[1:151,], aes(
    x = data_15[1:151, "pca1"], 
    y = data_15[1:151, "pca2"], 
    shape = as.factor(data_15[1:151,"euthymia"]), 
    color = as.factor(data_15[1:151,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_15[152:302,], aes(
    x = data_15[152:302, "pca1"], 
    y = data_15[152:302, "pca2"], 
    shape = as.factor(data_15[152:302,"euthymia"]), 
    color = as.factor(data_15[152:302,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))

plot1
plot2
plot_name <- paste0("pca1_15.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_15.png")
ggsave(plot_name, plot = plot2, bg = "white")
          
```

```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")

plot1 <- ggplot(data_15[1:151,], aes(
    x = data_15[1:151, "pca1"], 
    y = data_15[1:151, "pca2"], 
    shape = as.factor(data_15[1:151,"eu_50"]), 
    color = as.factor(data_15[1:151,"eu_50"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_15[152:302,], aes(
    x = data_15[152:302, "pca1"], 
    y = data_15[152:302, "pca2"], 
    shape = as.factor(data_15[152:302,"eu_50"]), 
    color = as.factor(data_15[152:302,"eu_50"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))

plot1
plot2
plot_name <- paste0("pca1_15_50.png")
ggsave(plot_name, plot = plot1, bg = "white", width = 2194, height = 1356, units = "px", dpi = 300)
plot_name <- paste0("pca2_15_50.png")
ggsave(plot_name, plot = plot2, bg = "white", width = 2194, height = 1356, units = "px", dpi = 300)
```


```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_15, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-1.5,1.5),y_limit=c(-1.5,3),iteration= iteration)
    modelik2 <- models(data_15, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-1.5,1.5),y_limit=c(-1.5,3), iteration = iteration)
    modelik3 <- models_dynamic(data_15,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-1.5,1.5),y_limit=c(-1.5,3), iteration = iteration)
    modelik4 <- models_dynamic(data_15,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-1.5,1.5),y_limit=c(-1.5,3), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik3$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
reconstruction_errors_3
reconstruction_errors_4
```
```{r}
all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_15 <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_15) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_15) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_15)


```
```{r}
accuracy_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
accuracy_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
precision_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
precision_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
recall_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
recall_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
f1_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
f1_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)

row_count=1
for (iteration in 1:10) {
  for (j in 1:3) {
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy3
    segment_accuracy_3 <- sapply(1:2, function(seg) {
      all_accuracy3[[iteration]][[j]][[seg]][, 2] 
    })
    segment_precision_3 <- sapply(1:2, function(seg) {
      all_precision3[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_3 <- sapply(1:2, function(seg) {
      all_recall3[[iteration]][[j]][[seg]][, 2]
    })
    segment_f3 <- sapply(1:2, function(seg) {
      all_f3[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_3[row_count, ] <- unlist(segment_accuracy_3)
    precision_matrix_3[row_count, ] <- unlist(segment_precision_3)
    recall_matrix_3[row_count, ] <- unlist(segment_recall_3)
    f1_matrix_3[row_count, ] <- unlist(segment_f3)
    
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy4
    segment_accuracy_4 <- sapply(1:2, function(seg) {
      all_accuracy4[[iteration]][[j]][[seg]][, 2]
    })
    segment_precision_4 <- sapply(1:2, function(seg) {
      all_precision4[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_4 <- sapply(1:2, function(seg) {
      all_recall4[[iteration]][[j]][[seg]][, 2]
    })
    segment_f4 <- sapply(1:2, function(seg) {
      all_f4[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_4[row_count, ] <- unlist(segment_accuracy_4)
    precision_matrix_4[row_count, ] <- unlist(segment_precision_4)
    recall_matrix_4[row_count, ] <- unlist(segment_recall_4)
    f1_matrix_4[row_count, ] <- unlist(segment_f4)
    
    row_count <- row_count + 1
  }
}

# Obliczanie średnich wartości dla każdej metryki, ignorując wartości NA
means_accuracy_3 <- colMeans(accuracy_matrix_3, na.rm = TRUE)
means_accuracy_4 <- colMeans(accuracy_matrix_4, na.rm = TRUE)
means_precision_3 <- colMeans(precision_matrix_3, na.rm = TRUE)
means_precision_4 <- colMeans(precision_matrix_4, na.rm = TRUE)
means_recall_3 <- colMeans(recall_matrix_3, na.rm = TRUE)
means_recall_4 <- colMeans(recall_matrix_4, na.rm = TRUE)
means_f1_3 <- colMeans(f1_matrix_3, na.rm = TRUE)
means_f1_4 <- colMeans(f1_matrix_4, na.rm = TRUE)

# Tworzenie macierzy wynikowej
result_matrix <- rbind(
  means_accuracy_3, means_accuracy_4,
  means_precision_3, means_precision_4,
  means_recall_3, means_recall_4,
  means_f1_3, means_f1_4
)

# Nazwy wierszy dla lepszej czytelności wyników
rownames(result_matrix) <- c(
  "Accuracy_3", "Accuracy_4",
  "Precision_3", "Precision_4",
  "Recall_3", "Recall_4",
  "F1_3", "F1_4"
)

# Drukowanie wynikowej macierzy
print(result_matrix)

```

```{r}
```
```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")
data_27 <- data_27 %>% select(-chunk)
plot1 <- ggplot(data_27[1:129,], aes(
    x = data_27[1:129, "pca1"], 
    y = data_27[1:129, "pca2"], 
    shape = as.factor(data_27[1:129,"euthymia"]), 
    color = as.factor(data_27[1:129,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_27[130:258,], aes(
    x = data_27[130:258, "pca1"], 
    y = data_27[130:258, "pca2"], 
    shape = as.factor(data_27[130:258,"euthymia"]), 
    color = as.factor(data_27[130:258,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_27.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_27.png")
ggsave(plot_name, plot = plot2, bg = "white")
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list() 
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_27, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(3,4),iteration= iteration)
    modelik2 <- models(data_27, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    #modelik3 <- models_dynamic(data_27,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    modelik4 <- models_dynamic(data_27,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik3$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
reconstruction_errors_3
reconstruction_errors_4
all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_27 <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_27) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_27) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_27)


colnames(wyniki_27) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_27)


```

```{r}
#data_27_smote <- data_27_smote[sample(nrow(data_27_smote)), ]
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")
data_27_smote <- data_27_smote %>% select(-chunk)
plot1 <- ggplot(data_27_smote[1:143,], aes(
    x = data_27_smote[1:143, "pca1"], 
    y = data_27_smote[1:143, "pca2"], 
    shape = as.factor(data_27_smote[1:143,"euthymia"]), 
    color = as.factor(data_27_smote[1:143,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_27_smote[144:287,], aes(
    x = data_27_smote[144:287, "pca1"], 
    y = data_27_smote[144:287, "pca2"], 
    shape = as.factor(data_27_smote[144:287,"euthymia"]), 
    color = as.factor(data_27_smote[144:287,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_27_smote.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_27_smote.png")
ggsave(plot_name, plot = plot2, bg = "white")
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list() 
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_27_smote, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(3,4),iteration= iteration)
    modelik2 <- models(data_27_smote, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    modelik3 <- models_dynamic(data_27_smote,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    modelik4 <- models_dynamic(data_27_smote,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
reconstruction_errors_3
reconstruction_errors_4
all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_27_smote <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_27_smote) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_27_smote) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_27_smote)



```

```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")

plot1 <- ggplot(data_20[1:151,], aes(
    x = data_20[1:151, "pca1"], 
    y = data_20[1:151, "pca2"], 
    shape = as.factor(data_20[1:151,"eu_50"]), 
    color = as.factor(data_20[1:151,"eu_50"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-4, 2.5)) +  
    ylim(c(-2.5, 5)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_20[152:302,], aes(
    x = data_20[152:302, "pca1"], 
    y = data_20[152:302, "pca2"], 
    shape = as.factor(data_20[152:302,"eu_50"]), 
    color = as.factor(data_20[152:302,"eu_50"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-4, 2.5)) +  
    ylim(c(-2.5, 5)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_20_50.png")
ggsave(plot_name, plot = plot1, bg = "white", width = 2194, height = 1356, units = "px", dpi = 300)
plot_name <- paste0("pca2_20_50.png")
ggsave(plot_name, plot = plot2, bg = "white", width = 2194, height = 1356, units = "px", dpi = 300)
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_20, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-4,2.5),y_limit=c(-2.5,5),iteration= iteration)
    modelik2 <- models(data_20, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-4,2.5),y_limit=c(-2.5,5), iteration = iteration)
    modelik3 <- models_dynamic(data_20,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-4,2.5),y_limit=c(-2.5,5), iteration = iteration)
    modelik4 <- models_dynamic(data_20,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-4,2.5),y_limit=c(-2.5,5), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
reconstruction_errors_3
reconstruction_errors_4
all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}

extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_20 <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_20) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_20) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_20)


```

```{r}
accuracy_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
accuracy_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
precision_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
precision_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
recall_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
recall_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)
f1_matrix_3 <- matrix(NA, nrow = 30, ncol = 2)
f1_matrix_4 <- matrix(NA, nrow = 30, ncol = 2)

row_count=1
for (iteration in 1:10) {
  for (j in 1:3) {
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy3
    segment_accuracy_3 <- sapply(1:2, function(seg) {
      all_accuracy3[[iteration]][[j]][[seg]][, 2] 
    })
    segment_precision_3 <- sapply(1:2, function(seg) {
      all_precision3[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_3 <- sapply(1:2, function(seg) {
      all_recall3[[iteration]][[j]][[seg]][, 2]
    })
    segment_f3 <- sapply(1:2, function(seg) {
      all_f3[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_3[row_count, ] <- unlist(segment_accuracy_3)
    precision_matrix_3[row_count, ] <- unlist(segment_precision_3)
    recall_matrix_3[row_count, ] <- unlist(segment_recall_3)
    f1_matrix_3[row_count, ] <- unlist(segment_f3)
    
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy4
    segment_accuracy_4 <- sapply(1:2, function(seg) {
      all_accuracy4[[iteration]][[j]][[seg]][, 2]
    })
    segment_precision_4 <- sapply(1:2, function(seg) {
      all_precision4[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_4 <- sapply(1:2, function(seg) {
      all_recall4[[iteration]][[j]][[seg]][, 2]
    })
    segment_f4 <- sapply(1:2, function(seg) {
      all_f4[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_4[row_count, ] <- unlist(segment_accuracy_4)
    precision_matrix_4[row_count, ] <- unlist(segment_precision_4)
    recall_matrix_4[row_count, ] <- unlist(segment_recall_4)
    f1_matrix_4[row_count, ] <- unlist(segment_f4)
    
    row_count <- row_count + 1
  }
}

# Obliczanie średnich wartości dla każdej metryki, ignorując wartości NA
means_accuracy_3 <- colMeans(accuracy_matrix_3, na.rm = TRUE)
means_accuracy_4 <- colMeans(accuracy_matrix_4, na.rm = TRUE)
means_precision_3 <- colMeans(precision_matrix_3, na.rm = TRUE)
means_precision_4 <- colMeans(precision_matrix_4, na.rm = TRUE)
means_recall_3 <- colMeans(recall_matrix_3, na.rm = TRUE)
means_recall_4 <- colMeans(recall_matrix_4, na.rm = TRUE)
means_f1_3 <- colMeans(f1_matrix_3, na.rm = TRUE)
means_f1_4 <- colMeans(f1_matrix_4, na.rm = TRUE)

# Tworzenie macierzy wynikowej
result_matrix <- rbind(
  means_accuracy_3, means_accuracy_4,
  means_precision_3, means_precision_4,
  means_recall_3, means_recall_4,
  means_f1_3, means_f1_4
)

# Nazwy wierszy dla lepszej czytelności wyników
rownames(result_matrix) <- c(
  "Accuracy_3", "Accuracy_4",
  "Precision_3", "Precision_4",
  "Recall_3", "Recall_4",
  "F1_3", "F1_4"
)

# Drukowanie wynikowej macierzy
print(result_matrix)

```
```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")
data_58 <- data_58 %>% select(-chunk)
plot1 <- ggplot(data_58[1:130,], aes(
    x = data_58[1:130, "pca1"], 
    y = data_58[1:130, "pca2"], 
    shape = as.factor(data_58[1:130,"euthymia"]), 
    color = as.factor(data_58[1:130,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-5, 5)) +  
    ylim(c(-4, 5)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_58[131:261,], aes(
    x = data_58[131:261, "pca1"], 
    y = data_58[131:261, "pca2"], 
    shape = as.factor(data_58[131:261,"euthymia"]), 
    color = as.factor(data_58[131:261,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-5, 5)) +  
    ylim(c(-4, 5)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_58.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_58.png")
ggsave(plot_name, plot = plot2, bg = "white")
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")
#data_58 <- data_58[-nrow(data_58), ]
for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_58, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-5,5),y_limit=c(-4,5),iteration= iteration)
    modelik2 <- models(data_58, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-5,5),y_limit=c(-4,5), iteration = iteration)
    modelik3 <- models_dynamic(data_58,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-5,5),y_limit=c(-4,5), iteration = iteration)
    modelik4 <- models_dynamic(data_58,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-5,5),y_limit=c(-4,5), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}

all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}

extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_58 <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_58) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_58) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_58) 

```


```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")
data_18 <- data_18 %>% select(-chunk)
plot1 <- ggplot(data_18[1:130,], aes(
    x = data_18[1:130, "pca1"], 
    y = data_18[1:130, "pca2"], 
    shape = as.factor(data_18[1:130,"euthymia"]), 
    color = as.factor(data_18[1:130,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-8, 8)) +  
    ylim(c(-8, 8)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_18[131:261,], aes(
    x = data_18[131:261, "pca1"], 
    y = data_18[131:261, "pca2"], 
    shape = as.factor(data_18[131:261,"euthymia"]), 
    color = as.factor(data_18[131:261,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-8,8)) +  
    ylim(c(-8,8)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_18.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_18.png")
ggsave(plot_name, plot = plot2, bg = "white")
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")
#data_18 <- data_18[-nrow(data_18), ]
for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_18, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-8,8),y_limit=c(-8,8),iteration= iteration)
    modelik2 <- models(data_18, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    modelik3 <- models_dynamic(data_18,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    modelik4 <- models_dynamic(data_18,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
all_V3
all_V4
reconstruction_errors_3
reconstruction_errors_4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}

extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_18 <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_18) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_18) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_18)


```

```{r}
shapes <- c("lack" = 3,"disease"=16,"euthymia"=17)
colors <- c("lack" = "grey","disease"="blue","euthymia"="green")
data_18_smote <- data_18_smote %>% select(-chunk)
plot1 <- ggplot(data_18_smote[1:144,], aes(
    x = data_18_smote[1:144, "pca1"], 
    y = data_18_smote[1:144, "pca2"], 
    shape = as.factor(data_18_smote[1:144,"euthymia"]), 
    color = as.factor(data_18_smote[1:144,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-8, 8)) +  
    ylim(c(-8, 8)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_18_smote[145:288,], aes(
    x = data_18_smote[145:288, "pca1"], 
    y = data_18_smote[145:288, "pca2"], 
    shape = as.factor(data_18_smote[145:288,"euthymia"]), 
    color = as.factor(data_18_smote[145:288,"euthymia"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-8,8)) +  
    ylim(c(-8,8)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
plot_name <- paste0("pca1_18_smote.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("pca2_18_smote.png")
ggsave(plot_name, plot = plot2, bg = "white")
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("eu_25","eu_50","eu_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(data_18_smote, n=2, p=0, C=2,"kmeans",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-8,8),y_limit=c(-8,8),iteration= iteration)
    modelik2 <- models(data_18_smote, n=2, p=0, C=2,"ssfcm",columns_pca,'euthymia',new_label,plot=FALSE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    modelik3 <- models_dynamic(data_18_smote,n=2,p=0,C=2,'dissfcm',columns_pca,'euthymia',new_label,plot=TRUE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    modelik4 <- models_dynamic(data_18_smote,n=2,p=0,C=2,'assfcm',columns_pca,'euthymia',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-8,8),y_limit=c(-8,8), iteration = iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
#all_V1
#all_V2
all_V3
all_V4
reconstruction_errors_3
reconstruction_errors_4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}

extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 3)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 3)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 3)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 3)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 3)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 3)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki_18_smote <- matrix(
  c(
    rowMeans(mean_accuracy_kmeans),
    apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_precision_kmeans),
    rowMeans(mean_recall_kmeans),
    rowMeans(mean_f1_kmeans),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 4
)

rownames(wyniki_18_smote) <- c('25%', '50%', '75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
colnames(wyniki_18_smote) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki_18_smote)


```

```{r,warnings=FALSE, message=FALSE,error=FALSE}
symulacja_1 <- function(n){
  symu <- data.frame(x1 = numeric(n), x2 = numeric(n), y = numeric(n))
  for (t in 1:n) {
    rand <- runif(1)
    if(t <=100){
      if (rand < 1/3) {
          symu$x1[t] <- rnorm(1, mean = 0, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 1.5, sd = 0.5)
          symu$y[t] <- 1
        } else if (rand >= 1/3 & rand < 2/3 ) {
          symu$x1[t] <- rnorm(1, mean = 1.5, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 2.5, sd = 0.5)
          symu$y[t] <- 2 
        } else {
          symu$x1[t] <- rnorm(1, mean = 3, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 3.5, sd = 0.5)
          symu$y[t] <- 3 
        }
    } else if(t > 100 & t <= 200){
      if (rand < 1/2) {
          symu$x1[t] <- rnorm(1, mean = 0.5, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 1.5, sd = 0.5)
          symu$y[t] <- 1
        } else {
          symu$x1[t] <- rnorm(1, mean = 2.5, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 3.5, sd = 0.5)
          symu$y[t] <- 3 
        }
    } #else if(t > 200 & t <= 300){
       # if (rand < 1/2) {
        #  symu$x1[t] <- rnorm(1, mean = 0.5, sd = 0.5)
        #  symu$x2[t] <- rnorm(1, mean = 1.5, sd = 0.5)
        #  symu$y[t] <- 'lack'
        #} else {
         # symu$x1[t] <- rnorm(1, mean = 2.5, sd = 0.5)
        #  symu$x2[t] <- rnorm(1, mean = 3.5, sd = 0.5)
        #  symu$y[t] <- 'lack' 
        #}
    #}
    else if(t > 200){
      if (rand < 1/2) {
          symu$x1[t] <- rnorm(1, mean = 0.5, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 1.5, sd = 0.5)
          symu$y[t] <- 4
      } else {
          symu$x1[t] <- rnorm(1, mean = 1, sd = 0.5)
          symu$x2[t] <- rnorm(1, mean = 2, sd = 0.5)
          symu$y[t] <- 2 
      }
    }
  }
  return(symu)
}

symulacja_zanik <- symulacja_1(n=300)
symulacja_zanik$y_25 <- do.call(rbind,chunki(symulacja_zanik,n=3,p=0.25,'y'))$cgic_1
symulacja_zanik$y_50  <- do.call(rbind,chunki(symulacja_zanik,n=3,p=0.5,'y'))$cgic_1
symulacja_zanik$y_75  <- do.call(rbind,chunki(symulacja_zanik,n=3,p=0.75,'y'))$cgic_1
```

```{r,warnings=FALSE, message=FALSE,error=FALSE}
symulacja_zanik$y <- as.factor(symulacja_zanik$y)
# Tworzenie wykresów dla każdego podzbioru danych
plot1 <- generate_plot(symulacja_zanik[1:100,],"y",1)
plot2 <- generate_plot(symulacja_zanik[101:200,],"y",2)
#plot3 <- generate_plot(symulacja_zanik[201:300,],"y_25",3)
plot3 <- generate_plot(symulacja_zanik[201:300,],"y",3)
plot1
plot2
plot3
plot_name <- paste0("sym1.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("sym2.png")
ggsave(plot_name, plot = plot2, bg = "white")
plot_name <- paste0("sym3.png")
ggsave(plot_name, plot = plot3, bg = "white")

plot1 <- generate_plot(symulacja_zanik[1:100,],"y_50",1)
plot2 <- generate_plot(symulacja_zanik[101:200,],"y_50",2)
#plot3 <- generate_plot(symulacja_zanik[201:300,],"y_25",3)
plot3 <- generate_plot(symulacja_zanik[201:300,],"y_50",3)
plot1
plot2
plot3
plot_name <- paste0("sym1_50.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("sym2_50.png")
ggsave(plot_name, plot = plot2, bg = "white")
plot_name <- paste0("sym3_50.png")
ggsave(plot_name, plot = plot3, bg = "white")

plot1 <- generate_plot(symulacja_zanik[1:100,],"y_75",1)
plot2 <- generate_plot(symulacja_zanik[101:200,],"y_75",2)
#plot3 <- generate_plot(symulacja_zanik[201:300,],"y_25",3)
plot3 <- generate_plot(symulacja_zanik[201:300,],"y_75",3)
plot1
plot2
plot3
plot_name <- paste0("sym1_75.png")
ggsave(plot_name, plot = plot1, bg = "white")
plot_name <- paste0("sym2_75.png")
ggsave(plot_name, plot = plot2, bg = "white")
plot_name <- paste0("sym3_75.png")
ggsave(plot_name, plot = plot3, bg = "white")
```

```{r,warnings=FALSE, message=FALSE,error=FALSE}
columns <- c("x1","x2")
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_precision1 <- list()
all_precision2 <- list()
all_precision3 <- list()
all_precision4 <- list()
all_recall1 <- list()
all_recall2 <- list()
all_recall3 <- list()
all_recall4 <- list()
all_f1 <- list()
all_f2 <- list()
all_f3 <- list()
all_f4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
columns_pca <- c("pca1","pca2")
new_labels <- c("y_25","y_50","y_75")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  precision1 <- list()
  precision2 <- list()
  precision3 <- list()
  precision4 <- list()
  recall1 <- list()
  recall2 <- list()
  recall3 <- list()
  recall4 <- list()
  f1 <- list()
  f2 <- list()
  f3 <- list()
  f4 <- list()
  V3 <- list()
  V4 <- list()
  reconstruction_error_3 <- list()
  reconstruction_error_4 <- list()
  for (i in 1:3){
    new_label <- new_labels[i]
    modelik1 <- models(symulacja_zanik, n=3, p=0, C=3,"kmeans",columns,'y',new_label, plot=TRUE, x_limit=c(-1,4), y_limit=c(-1.5,5), iteration=iteration)
    modelik2 <- models(symulacja_zanik, n=3, p=0, C=3,"ssfcm",columns,'y',new_label, plot=TRUE, x_limit=c(-1,4), y_limit=c(-1.5,5), iteration=iteration)
    modelik3 <- models_dynamic(data=symulacja_zanik,n=3,p=0,C=3,method='dissfcm',selected_columns=columns,label_column='y',new_label=new_label, plot=TRUE, x_limit=c(-1,4), y_limit=c(-1.5,5), iteration=iteration)
    modelik4 <- models_dynamic(symulacja_zanik,n=3,p=0,C=3,'assfcm',columns,'y',new_label,threshold = 0.3, plot=TRUE, x_limit=c(-1,4), y_limit=c(-1.5,5), iteration=iteration)
    accuracy1[[i]] <- modelik1$accuracy
    accuracy2[[i]] <- modelik2$accuracy
    accuracy3[[i]] <- modelik3$accuracy
    accuracy4[[i]] <- modelik4$accuracy
    precision1[[i]] <- modelik1$precision
    precision2[[i]] <- modelik2$precision
    precision3[[i]] <- modelik3$precision
    precision4[[i]] <- modelik4$precision
    recall1[[i]] <- modelik1$recall
    recall2[[i]] <- modelik2$recall
    recall3[[i]] <- modelik3$recall
    recall4[[i]] <- modelik4$recall
    f1[[i]] <- modelik1$f1
    f2[[i]] <- modelik2$f1
    f3[[i]] <- modelik3$f1
    f4[[i]] <- modelik4$f1
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
    reconstruction_error_3[[i]] <- modelik3$reconstruction_error
    reconstruction_error_4[[i]] <- modelik4$reconstruction_error
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_precision1[[iteration]] <- precision1
  all_precision2[[iteration]] <- precision2
  all_precision3[[iteration]] <- precision3
  all_precision4[[iteration]] <- precision4
  all_recall1[[iteration]] <- recall1
  all_recall2[[iteration]] <- recall2
  all_recall3[[iteration]] <- recall3
  all_recall4[[iteration]] <- recall4
  all_f1[[iteration]] <- f1
  all_f2[[iteration]] <- f2
  all_f3[[iteration]] <- f3
  all_f4[[iteration]] <- f4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
  reconstruction_errors_3[[iteration]] <- reconstruction_error_3
  reconstruction_errors_4[[iteration]] <- reconstruction_error_4
}


```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
all_V3
all_V4
reconstruction_errors_3
reconstruction_errors_4
```

```{r,warnings=FALSE, message=FALSE,error=FALSE}

extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_accuracy_kmeans <- list()
all_accuracy_ssfcm <- list()
all_accuracy_dissfcm <- list()
all_accuracy_assfcm <- list()
all_precision_kmeans <- list()
all_precision_ssfcm <- list()
all_precision_dissfcm <- list()
all_precision_assfcm <- list()
all_recall_kmeans <- list()
all_recall_ssfcm <- list()
all_recall_dissfcm <- list()
all_recall_assfcm <- list()
all_f1_kmeans <- list()
all_f1_ssfcm <- list()
all_f1_dissfcm <- list()
all_f1_assfcm <- list()

for (iteration in 1:10) {
  all_accuracy_kmeans[[iteration]] <- extract_and_calculate(all_accuracy1[[iteration]], 4)
  all_accuracy_ssfcm[[iteration]] <- extract_and_calculate(all_accuracy2[[iteration]], 4)
  all_accuracy_dissfcm[[iteration]] <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  all_accuracy_assfcm[[iteration]] <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_precision_kmeans[[iteration]] <- extract_and_calculate(all_precision1[[iteration]], 4)
  all_precision_ssfcm[[iteration]] <- extract_and_calculate(all_precision2[[iteration]], 4)
  all_precision_dissfcm[[iteration]] <- sapply(all_precision3[[iteration]], mean_without_zeros)
  all_precision_assfcm[[iteration]] <- sapply(all_precision4[[iteration]], mean_without_zeros)
 
  all_recall_kmeans[[iteration]] <- extract_and_calculate(all_recall1[[iteration]], 4)
  all_recall_ssfcm[[iteration]] <- extract_and_calculate(all_recall2[[iteration]], 4)
  all_recall_dissfcm[[iteration]] <- sapply(all_recall3[[iteration]], mean_without_zeros)
  all_recall_assfcm[[iteration]] <- sapply(all_recall4[[iteration]], mean_without_zeros)
 
  all_f1_kmeans[[iteration]] <- extract_and_calculate(all_f1[[iteration]], 4)
  all_f1_ssfcm[[iteration]] <- extract_and_calculate(all_f2[[iteration]], 4)
  all_f1_dissfcm[[iteration]] <- sapply(all_f3[[iteration]], mean_without_zeros)
  all_f1_assfcm[[iteration]] <- sapply(all_f4[[iteration]], mean_without_zeros)
}

combined_accuracy_kmeans <- do.call(c, all_accuracy_kmeans)
combined_accuracy_ssfcm <- do.call(c, all_accuracy_ssfcm)
combined_accuracy_dissfcm <- do.call(c, all_accuracy_dissfcm)
combined_accuracy_assfcm <- do.call(c, all_accuracy_assfcm)

mean_accuracy_kmeans <- matrix(as.numeric(combined_accuracy_kmeans), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_accuracy_ssfcm), nrow = 3, byrow = TRUE)
mean_accuracy_dissfcm <- matrix(as.numeric(combined_accuracy_dissfcm), nrow = 3, byrow = TRUE)
mean_accuracy_assfcm <- matrix(as.numeric(combined_accuracy_assfcm), nrow = 3, byrow = TRUE)

combined_precision_kmeans <- do.call(c, all_precision_kmeans)
combined_precision_ssfcm <- do.call(c, all_precision_ssfcm)
combined_precision_dissfcm <- do.call(c, all_precision_dissfcm)
combined_precision_assfcm <- do.call(c, all_precision_assfcm)

mean_precision_kmeans <- matrix(as.numeric(combined_precision_kmeans), nrow = 3, byrow = TRUE)
mean_precision_ssfcm <- matrix(as.numeric(combined_precision_ssfcm), nrow = 3, byrow = TRUE)
mean_precision_dissfcm <- matrix(as.numeric(combined_precision_dissfcm), nrow = 3, byrow = TRUE)
mean_precision_assfcm <- matrix(as.numeric(combined_precision_assfcm), nrow = 3, byrow = TRUE)

combined_recall_kmeans <- do.call(c, all_recall_kmeans)
combined_recall_ssfcm <- do.call(c, all_recall_ssfcm)
combined_recall_dissfcm <- do.call(c, all_recall_dissfcm)
combined_recall_assfcm <- do.call(c, all_recall_assfcm)

mean_recall_kmeans <- matrix(as.numeric(combined_recall_kmeans), nrow = 3, byrow = TRUE)
mean_recall_ssfcm <- matrix(as.numeric(combined_recall_ssfcm), nrow = 3, byrow = TRUE)
mean_recall_dissfcm <- matrix(as.numeric(combined_recall_dissfcm), nrow = 3, byrow = TRUE)
mean_recall_assfcm <- matrix(as.numeric(combined_recall_assfcm), nrow = 3, byrow = TRUE)

combined_f1_kmeans <- do.call(c, all_f1_kmeans)
combined_f1_ssfcm <- do.call(c, all_f1_ssfcm)
combined_f1_dissfcm <- do.call(c, all_f1_dissfcm)
combined_f1_assfcm <- do.call(c, all_f1_assfcm)

mean_f1_kmeans <- matrix(as.numeric(combined_f1_kmeans), nrow = 3, byrow = TRUE)
mean_f1_ssfcm <- matrix(as.numeric(combined_f1_ssfcm), nrow = 3, byrow = TRUE)
mean_f1_dissfcm <- matrix(as.numeric(combined_f1_dissfcm), nrow = 3, byrow = TRUE)
mean_f1_assfcm <- matrix(as.numeric(combined_f1_assfcm), nrow = 3, byrow = TRUE)

wyniki <- matrix(
  c(
    #rowMeans(mean_accuracy_kmeans),
    #apply(mean_accuracy_kmeans, 1, sd),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_precision_ssfcm),
    rowMeans(mean_recall_ssfcm),
    rowMeans(mean_f1_ssfcm),
    rowMeans(mean_accuracy_dissfcm),
    apply(mean_accuracy_dissfcm, 1, sd),
    rowMeans(mean_precision_dissfcm),
    rowMeans(mean_recall_dissfcm),
    rowMeans(mean_f1_dissfcm),
    rowMeans(mean_accuracy_assfcm),
    apply(mean_accuracy_assfcm, 1, sd),
    rowMeans(mean_precision_assfcm),
    rowMeans(mean_recall_assfcm),
    rowMeans(mean_f1_assfcm)
  ), 
  ncol = 3
)

rownames(wyniki) <- c('25%', '50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%','25%','50%','75%')
#colnames(wyniki) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
colnames(wyniki) <- c('ssfcm','dissfcm', 'assfcm')
print(wyniki)


```

```{r}
text<-all_accuracy1
extract_accuracy <- function(text) {
  as.numeric(sub(".*accuracy: ([0-9\\.]+).*", "\\1", text))
}

n_elements <- length(all_accuracy1)


matrix_all_1 <- matrix(0, ncol = n_elements * 3, nrow = 4)
matrix_all_2 <- matrix(0, ncol = n_elements * 3, nrow = 4)

for (i in 1:n_elements) {
  chunk_matrices_1 <- sapply(1:3, function(j) extract_accuracy(all_accuracy1[[i]][[j]][1:4]))
  chunk_matrices_2 <- sapply(1:3, function(j) extract_accuracy(all_accuracy2[[i]][[j]][1:4]))
  
 
  matrix_all_1[, ((i-1)*3 + 1):(i*3)] <- chunk_matrices_1
  matrix_all_2[, ((i-1)*3 + 1):(i*3)] <- chunk_matrices_2
}


accuracy_matrix_3 <- matrix(NA, nrow = 30, ncol = 3)
accuracy_matrix_4 <- matrix(NA, nrow = 30, ncol = 3)
precision_matrix_3 <- matrix(NA, nrow = 30, ncol = 3)
precision_matrix_4 <- matrix(NA, nrow = 30, ncol = 3)
recall_matrix_3 <- matrix(NA, nrow = 30, ncol = 3)
recall_matrix_4 <- matrix(NA, nrow = 30, ncol = 3)
f1_matrix_3 <- matrix(NA, nrow = 30, ncol = 3)
f1_matrix_4 <- matrix(NA, nrow = 30, ncol = 3)
row_count <- 1


for (iteration in 1:10) {
  for (j in 1:3) {
    segment_accuracies <- sapply(1:3, function(seg) {
      all_accuracy3[[iteration]][[j]][[seg]][, 2] 
    })
    accuracy_matrix_3[row_count, ] <- unlist(segment_accuracies)
    segment_accuracies <- sapply(1:3, function(seg) {
      all_accuracy4[[iteration]][[j]][[seg]][, 2] 
    })
    accuracy_matrix_4[row_count, ] <- unlist(segment_accuracies)
    row_count <- row_count + 1
  }
}


#print(accuracy_matrix_3)
means_1 <- rowMeans(accuracy_matrix_1, na.rm = TRUE)
means_2 <- rowMeans(accuracy_matrix_2, na.rm = TRUE)
means_3 <- colMeans(accuracy_matrix_3, na.rm = TRUE)
means_4 <- colMeans(accuracy_matrix_4, na.rm = TRUE)
result_matrix <- rbind(means_1, means_2, means_3, means_4)
print(result_matrix)
```

```{r}
row_count=1
for (iteration in 1:10) {
  for (j in 1:3) {
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy3
    segment_accuracy_3 <- sapply(1:3, function(seg) {
      all_accuracy3[[iteration]][[j]][[seg]][, 2] 
    })
    segment_precision_3 <- sapply(1:3, function(seg) {
      all_precision3[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_3 <- sapply(1:3, function(seg) {
      all_recall3[[iteration]][[j]][[seg]][, 2]
    })
    segment_f3 <- sapply(1:3, function(seg) {
      all_f3[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_3[row_count, ] <- unlist(segment_accuracy_3)
    precision_matrix_3[row_count, ] <- unlist(segment_precision_3)
    recall_matrix_3[row_count, ] <- unlist(segment_recall_3)
    f1_matrix_3[row_count, ] <- unlist(segment_f3)
    
    # Ekstrakcja accuracy, precision, recall i f1 dla accuracy4
    segment_accuracy_4 <- sapply(1:3, function(seg) {
      all_accuracy4[[iteration]][[j]][[seg]][, 2]
    })
    segment_precision_4 <- sapply(1:3, function(seg) {
      all_precision4[[iteration]][[j]][[seg]][, 2]
    })
    segment_recall_4 <- sapply(1:3, function(seg) {
      all_recall4[[iteration]][[j]][[seg]][, 2]
    })
    segment_f4 <- sapply(1:3, function(seg) {
      all_f4[[iteration]][[j]][[seg]][, 2]
    })

    # Wstawianie wyników do odpowiednich macierzy
    accuracy_matrix_4[row_count, ] <- unlist(segment_accuracy_4)
    precision_matrix_4[row_count, ] <- unlist(segment_precision_4)
    recall_matrix_4[row_count, ] <- unlist(segment_recall_4)
    f1_matrix_4[row_count, ] <- unlist(segment_f4)
    
    row_count <- row_count + 1
  }
}

# Obliczanie średnich wartości dla każdej metryki, ignorując wartości NA
means_accuracy_3 <- colMeans(accuracy_matrix_3, na.rm = TRUE)
means_accuracy_4 <- colMeans(accuracy_matrix_4, na.rm = TRUE)
means_precision_3 <- colMeans(precision_matrix_3, na.rm = TRUE)
means_precision_4 <- colMeans(precision_matrix_4, na.rm = TRUE)
means_recall_3 <- colMeans(recall_matrix_3, na.rm = TRUE)
means_recall_4 <- colMeans(recall_matrix_4, na.rm = TRUE)
means_f1_3 <- colMeans(f1_matrix_3, na.rm = TRUE)
means_f1_4 <- colMeans(f1_matrix_4, na.rm = TRUE)

# Tworzenie macierzy wynikowej
result_matrix <- rbind(
  means_accuracy_3, means_accuracy_4,
  means_precision_3, means_precision_4,
  means_recall_3, means_recall_4,
  means_f1_3, means_f1_4
)

# Nazwy wierszy dla lepszej czytelności wyników
rownames(result_matrix) <- c(
  "Accuracy_3", "Accuracy_4",
  "Precision_3", "Precision_4",
  "Recall_3", "Recall_4",
  "F1_3", "F1_4"
)

# Drukowanie wynikowej macierzy
print(result_matrix)

```

#wiele klas 
```{r}
shapes <- c("lack" = 3,"depression"=16,"euthymia"=17,"mania"=13)
colors <- c("lack" = "grey","depression"="blue","euthymia"="green","mania"="orange")

plot1 <- ggplot(data_15[1:151,], aes(
    x = data_15[1:151, "pca1"], 
    y = data_15[1:151, "pca2"], 
    shape = as.factor(data_15[1:151,"cgic"]), 
    color = as.factor(data_15[1:151,"cgic"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_15[152:302,], aes(
    x = data_15[152:302, "pca1"], 
    y = data_15[152:302, "pca2"], 
    shape = as.factor(data_15[152:302,"cgic"]), 
    color = as.factor(data_15[152:302,"cgic"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-1.5, 1.5)) +  
    ylim(c(-1.5, 3)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))

plot1
plot2
```
```{r}
shapes <- c("lack" = 3,"depression"=16,"euthymia"=17,"mania"=15)
colors <- c("lack" = "grey","depression"="blue","euthymia"="green","mania"="orange")

plot1 <- ggplot(data_27[1:129,], aes(
    x = data_27[1:129, "pca1"], 
    y = data_27[1:129, "pca2"], 
    shape = as.factor(data_27[1:129,"cgic"]), 
    color = as.factor(data_27[1:129,"cgic"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",1), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) + 
    scale_color_manual(values = colors) + 
    guides(color = guide_legend(override.aes = list(shape = 15)))
plot2 <- ggplot(data_27[130:258,], aes(
    x = data_27[130:258, "pca1"], 
    y = data_27[130:258, "pca2"], 
    shape = as.factor(data_27[130:258,"cgic"]), 
    color = as.factor(data_27[130:258,"cgic"])
)) +
    geom_point(size = 3, stroke = 0.5) +
    labs(
        title = paste("Chunk",2), 
        x = "pca1", 
        y = "pca2",
        shape = "Observed",
        color = "Observed"
    ) +
    xlim(c(-2, 3)) +  
    ylim(c(-4, 4)) + 
    theme_minimal() +
    theme(
        legend.text = element_text(size = 22),        
        legend.title = element_text(size = 24),       
        plot.title = element_text(size = 26, face = "bold"),  
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 22),       
        axis.title.y = element_text(size = 22)           
    ) +
    scale_shape_manual(values = shapes) +  # Dodajemy własne kształty
    scale_color_manual(values = colors) +  # Opcjonalnie dodajemy własne kolory
    guides(color = guide_legend(override.aes = list(shape = 15)))  # Ustawienia

plot1
plot2
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
all_accuracy1 <- list()
all_accuracy2 <- list()
all_accuracy3 <- list()
all_accuracy4 <- list()
all_V3 <- list()
all_V4 <- list()
reconstruction_errors_3 <- list()
reconstruction_errors_4 <- list()
new_labels <- c("cgic_25","cgic_50","cgic_75")
columns_pca <- c("pca1","pca2")

for (iteration in 1:10) {
  accuracy1 <- list()
  accuracy2 <- list()
  accuracy3 <- list()
  accuracy4 <- list()
  V3 <- list()
  V4 <- list() 
  for (i in 1:2){
    new_label <- new_labels[i]
    modelik1 <- models(data_27, n=2, p=0, C=3,"kmeans",columns_pca,'cgic',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(3,4),iteration= iteration)
    modelik2 <- models(data_27, n=2, p=0, C=3,"ssfcm",columns_pca,'cgic',new_label,plot=FALSE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    modelik3 <- models_dynamic(data_27,n=2,p=0,C=3,'dissfcm',columns_pca,'cgic',new_label,plot=TRUE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    modelik4 <- models_dynamic(data_27,n=2,p=0,C=3,'assfcm',columns_pca,'cgic',new_label,threshold = 0.3,plot=TRUE,x_limit=c(-2,2),y_limit=c(-3,4), iteration = iteration)
    accuracy1[[i]] <- modelik1$results
    accuracy2[[i]] <- modelik2$results
    accuracy3[[i]] <- modelik3$results
    accuracy4[[i]] <- modelik4$results
    V3[[i]] <- modelik3$v_matrices
    V4[[i]] <- modelik4$v_matrices
  }
  all_accuracy1[[iteration]] <- accuracy1
  all_accuracy2[[iteration]] <- accuracy2
  all_accuracy3[[iteration]] <- accuracy3
  all_accuracy4[[iteration]] <- accuracy4
  all_V3[[iteration]] <- V3
  all_V4[[iteration]] <- V4
}
```
```{r}
accuracy1
accuracy2
accuracy3
accuracy4
```
```{r}
#all_V1
#all_V2
all_V3
all_V4
```
```{r,warnings=FALSE, message=FALSE,error=FALSE}
extract_and_calculate <- function(results_list, index) {
  sapply(results_list, function(x) x[[index]])
}

all_wynikik_5 <- list()
all_wynikic_5 <- list()
all_wyniki_dissfcm_means <- list()
all_wyniki_assfcm_means <- list()

for (iteration in 1:10) {
  wynikik_5 <- extract_and_calculate(all_accuracy1[[iteration]], 3)
  wynikic_5 <- extract_and_calculate(all_accuracy2[[iteration]], 3)
  wyniki_dissfcm_means <- sapply(all_accuracy3[[iteration]], mean_without_zeros)
  wyniki_assfcm_means <- sapply(all_accuracy4[[iteration]], mean_without_zeros)
  
  all_wynikik_5[[iteration]] <- wynikik_5
  all_wynikic_5[[iteration]] <- wynikic_5
  all_wyniki_dissfcm_means[[iteration]] <- wyniki_dissfcm_means
  all_wyniki_assfcm_means[[iteration]] <- wyniki_assfcm_means
}

combined_wynikik_5 <- do.call(c, all_wynikik_5)
combined_wynikic_5 <- do.call(c, all_wynikic_5)
combined_wyniki_dissfcm_means <- do.call(c, all_wyniki_dissfcm_means)
combined_wyniki_assfcm_means <- do.call(c, all_wyniki_assfcm_means)

mean_wynikik_5 <- matrix(as.numeric(combined_wynikik_5), nrow = 3, byrow = TRUE)
mean_accuracy_ssfcm <- matrix(as.numeric(combined_wynikic_5), nrow = 3, byrow = TRUE)
mean_wyniki_dissfcm_means <- matrix(as.numeric(combined_wyniki_dissfcm_means), nrow = 3, byrow = TRUE)
mean_wyniki_assfcm_means <- matrix(as.numeric(combined_wyniki_assfcm_means), nrow = 3, byrow = TRUE)

wyniki <- matrix(
  c(
    rowMeans(mean_wynikik_5),
    apply(mean_wynikik_5, 1, sd),
    rowMeans(mean_accuracy_ssfcm),
    apply(mean_accuracy_ssfcm, 1, sd),
    rowMeans(mean_wyniki_dissfcm_means),
    apply(mean_wyniki_dissfcm_means, 1, sd),
    rowMeans(mean_wyniki_assfcm_means),
    apply(mean_wyniki_assfcm_means, 1, sd)
  ), 
  ncol = 4
)

rownames(wyniki) <- c('25%', '50%', '75%','25%','50%','75%')
colnames(wyniki) <- c('kmeans','ssfcm','dissfcm', 'assfcm')
print(wyniki)


```

